parserOptions:
  ecmaVersion: 6
  project: tsconfig.json

  env:
  node: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended

rules:
  react/react-in-jsx-scope: off
  react/jsx-props-no-spreading: off
